language: go

go:
  - 1.14

cache:
  directories:
    - .build

before_script:
  - chown --recursive travis:travis .build && rmdir --ignore-fail-on-non-empty .build

script:
  - >-
    make all
    POST_GENERATE='git diff --exit-code'
    POST_FMT='git diff --exit-code'
    GO_TEST_FLAGS='-race -coverprofile=coverage.txt'

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt -X fix
